### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by mhdbashar** [ZulNs/ZulNs.github.io#1]
Please provide me this file, I used it before and I get 404 now.
https://ZulNs.github.io/libs/calendar.css

**Comment by ZulNs** [comment]
Sorry, it discontinued. But, there's a new version
https://github.com/ZulNs/Datepicker.js or
https://github.com/ZulNs/Calendar.js

**Comment by mhdbashar** [comment]
Thanks, 
But I used this library and I forced to use this missing link
I hope to help me find "calender.css" file.

**Comment by ZulNs** [comment]
Now I have just recreated [libs repo](https://github.com/ZulNs/libs) to restore my old libs, especially [calendar.css](https://zulns.github.io/libs/calendar.css).
